[package]
name = "min_os"
version = "0.1.0"
authors = ["Joe Chasinga <jo.chasinga@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-min_os.json"